apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rwou
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0051-tenant/tkrw-pr712-0075-0051-app/devfile-sample-rwou@sha256:a585237f3e55204bf62a6529eb5aa52408de6f137933523a9ebd7d4d4f77c4ec
        name: my-nodejs
        resources: {}
status: {}
